[package]
name = "rusty-lander"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
